name: Deploy to Fly
on: [push]
jobs:  
  autodeploy:    
    runs-on: ubuntu-latest    
    env:      
      FLY_API_TOKEN: ${{secrets.FLY_API_TOKEN}}
      # This step checks out a copy of your repository.
    - uses: actions/checkout@v2
    # This step runs `flyctl deploy`.
    - name: Install flyctl via https://github.com/superfly/flyctl-actions
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy
      run: flyctl deploy --dockerfile .\Dockerfile